### ISSUE TITLE
ON HOLD:Reactivity Data - Individual Applications Table[PDP]

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#13]
![image](https://github.com/user-attachments/assets/4b575f0e-3a40-4553-b9cf-604f89ab74fd)

**Comment by venkateshamkeerthi** [comment]
Analysis completed.
**Primary Antibody all applications data :**
response[0].raw.reactivitytabledata

Tested(TESTED_AND_REACTS): double check green( Tested)
REACTS: single check green(Expected)
EXPECTED_TO_REACTS: Predicted orange(Predicted)
NO_EXPERIMENTAL_DATA_EXPECTED_TO_REACT: Not Recommended Red

**Secondary and other products applications data:**
JSON.parse(response[0].raw.reactivityjson).applications

Tab: [0].name
Species: [0].species[0].name   Species
Dilution info: [0].species[0].recommendedDilution Dilution info
[0].species[0].notes Notes
[4].species

**sample urls:**
/en-us/products/primary-antibodies/histone-h3-antibody-nuclear-marker-and-chip-grade-ab1791
/en-us/products/secondary-antibodies/goat-rabbit-igg-h-l-alexa-fluor-488-ab150077
/en-us/products/elisa-kits/human-tnf-alpha-elisa-kit-ab181421

**Comment by venkateshamkeerthi** [comment]
working on primary antibodies button(click) logic  using eventlisteners on product reactivity data

**Comment by venkateshamkeerthi** [comment]
need individual application mapping for images and publications, we sent email to David.
also single JSON file for ReactivityData instead of multiple JSON.

fetching Reactivity All Application data from raw.reactivitytabledata JSON and 
Individual application fields are available in the raw.reactivityjson.applications JSON but species.suitability data is not updated correctly (all species data is updated values with ‘"NO_EXPERIMENTAL_DATA_EXPECTED_TO_REACT" in JSON.

Can you please update all information(Reactivity All Application and Individual Application data in single raw.reactivitytabledata JSON by updating 
2 fileds species.recommendedDilution and species.notes.
@davenichols-DHLS

**Comment by venkateshamkeerthi** [comment]
asp discussed with David "Abcam caches their data for 30 days so their site might be slightly out of date."
and meged requested fields in  raw.reactivitytabledata JSON and I resumed working on this task.
Note: I am not working publications and images filtering until we get clarification from David, presently publications and images json is not having application name(mapping)

**Comment by venkateshamkeerthi** [comment]
on hold until priority UE(Universal Editor ) blocks task is complete.
I will resume once the UE blocks completed

**Comment by Meenu-GSPANN** [comment]
Closing the issue due to the design changed
