### ISSUE TITLE
[Webinar] Detail Page(Logged User)

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#174]
- [x] Back to Navigation
- [x] Column[Reuse]
- [x] Title[Reuse]
- [x] Text[Reuse]
- [x] Learn More
- [x] Columns(More Episode)
- [x] RelatedStory (You may be interseted in)

Figma Designs: https://www.figma.com/design/0MPkm5mzMfI0UPS6DWdbKs/Optimus-%2F-Abcam-Website-Designs?node-id=2030-11781&node-type=section&t=oiOLqNYEnznjpWOF-0

**Comment by venkateshamkeerthi** [comment]
Started analyzing above specified components

**Comment by venkateshamkeerthi** [comment]
Naveen(@Naveen-Ramgiri ) is working on "Learn More" component  with issue#288 and
 RelatedStory (You may be interseted in) is need to test after indexing completed

**Comment by venkateshamkeerthi** [comment]
completed development for related-stories block and raised PR but  we can test after index data updated in
/en-us/webinar/query-index.json and publish data also we can work after indexing.
as discussed with Ravi and Shivangi "On Deman |Views " we implement after post releases since we don't have any inputs for this

**Comment by venkateshamkeerthi** [comment]
c
