### ISSUE TITLE
[OneTrust] Recommendation for changes to the OneTrust implementation at abcam

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#531]
Remove OneTrust and LiveChat from the codebase, as these will be run from GTM.

DO NOT MERGE THIS CHANGE WHEN DONE.  We need to coordinate with the GTM team.

**Comment by pardeepgera23** [comment]
Removed current OneTrust and LiveChat code in branch **531-Remove-OT-Livechat**

**Comment by davenichols-DHLS** [comment]
Sorry, this is not the same thing.  FYI @Meenu-GSPANN , @pardeepgera23  and @rgravitvl .

The other issue was GTM on the author.  This issue is to remove FreshChat AND OneTrust from running in the code base, as they will run in GTM.

**Comment by pardeepgera23** [comment]
Hi @davenichols-DHLS  - I had done the same only. I had removed FreshChat AND OneTrust in a feature branch **531-Remove-OT-Livechat** but didn't merge to main as per your suggestion.

Now, since you have included the same changes in another branch also [554-seo-move-datalayer], do we need to keep this issue open ?

**Comment by pardeepgera23** [comment]
Closing this task as OneTrust and FreshChat have been removed from code and merged into main as part of #554
