### ISSUE TITLE
[Stories] Embed Podcast Implementation

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#73]
Figma design:-
https://www.figma.com/design/0MPkm5mzMfI0UPS6DWdbKs/Primary-Antibodies-Landing-Page?node-id=252-28&t=oNLbv7ehIhFSQENE-1

**Comment by Rajesh-GSPANN** [comment]
Hi ,
Started working on the audio podcast. Currently implementing on the hero video.
![image](https://github.com/user-attachments/assets/91e94eac-0844-4f38-b6ee-4772f4e16e4f)

CC: @Meenu-GSPANN @pardeepgera23  @rgravitvl

**Comment by Rajesh-GSPANN** [comment]
Hi,
Functionality has been done. Able to play the Audio on click.  UI is in progress.

@shivangi1422 @rgravitvl  I think we need introduce new filed to the 'Media' block, since we need to have the Text to show on top of the icon(Listen to the Audio)Attached the screenshot in the above comment. The text which we have now is to the link text. 

CC: @Meenu-GSPANN @pardeepgera23

**Comment by Rajesh-GSPANN** [comment]
Hi @shivangi1422 ,
I am done with functionality . We can integrate our code and raise single PR. Let me once you raise and merge PR. I will close the ticket. 

CC: @pardeepgera23 @Meenu-GSPANN

**Comment by Rajesh-GSPANN** [comment]
Hi @Meenu-GSPANN  @shivangi1422 ,
Now the changes are available in main branch. Hence closing the ticket.

CC: @pardeepgera23
